### PR TITLE
Request header parameter fix

### PR DESCRIPTION
**Pull request by miranovy**
Header request parameter "X-Auth-Token" should be provided.

`$request->getHeaders()` return headers names with upper letters (e.g. `X-Auth-Token`) and condition on line 135 (https://github.com/contributte/apitte/blob/master/src/Mapping/RequestParameterMapping.php#L135) is false becouse `$headerParameterName` always contains parameter name (e.g. `x-auth-token`) with lower letters. Therefore, I converted everything to lowercase.

### CODE REVIEW

**Comment by f3l1x** [comment]
Nice. Can you please add some tests?

**Comment by miranovy** [comment]
Added test containing header name in uppercase and lowercase letters

**Comment by f3l1x** [comment]
Can you rebase it @miranovy?

**Comment by f3l1x** [comment]
Resolved via https://github.com/contributte/apitte/pull/188

**Pull request closed without merging**
