### PR TITLE
Update EndpointParameter.php

### PR DESCRIPTION
**Pull request by Domm98CZ**
Edited datatypes due to openapi validation error.

image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the PR. Is this still relevant on the latest version?

**Comment by f3l1x** [comment]
ping @Domm98CZ

**Comment by Domm98CZ** [comment]
Yes, PR is still relevant on dev-master.

**Comment by f3l1x** [comment]
Can you fix tests?

**Comment by Domm98CZ** [comment]
Closing this PR.

-> https://github.com/contributte/apitte/pull/184

**Pull request closed without merging**
